### ISSUE TITLE
GraphiQL JS error with tartiflette 1.0RC1

### ISSUE THREAD

**Issue by aljinovic** [tartiflette/tartiflette-aiohttp#45]
I've been testing the tartiflette RC1 (https://github.com/tartiflette/tartiflette/pull/272) with tartiflette-aiohttp and noticed that GraphiQL crashes with this error:

```
GraphQLError: Syntax Error: Expected <EOF>, found Name "longer"
    at syntaxError (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:23522:10)
    at expect (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:28513:32)
    at parseValue (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:27279:3)
    at buildInputValue (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33676:118)
    at https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:25955:31
    at Array.reduce (<anonymous>)
    at keyValMap (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:25954:15)
    at buildInputValueDefMap (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33669:36)
    at buildDirective (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33696:13)
    at Array.map (<anonymous>)
```

**Comment by Maximilien-R** [comment]
Hi @aljinovic,

Thank you for raising this issue.

After a quick investigation, the error seems to be related to the SDL parsing made in `tartiflette` side more than to an error in `tartiflette-aiohttp` and/or GraphiQL.

Both [`StringValue`](https://graphql.github.io/graphql-spec/June2018/#StringValue) and [`BlockString`](https://graphql.github.io/graphql-spec/June2018/#BlockStringCharacter) don't seem to be properly parsed by our SDL parser (build on top of `lark-parser`).

We'll dig into it and keep you in touch.

(I'm transferring this issue to the `tartiflette` repository)
